### ISSUE TITLE
missing pages

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#10]
1- Contributions game - Total Earnings page
2- Example
3-Understandings Questions
4- Summary page

I will share the updated example, understanding, and summary pages with you. Until then, you can code the total earnings page.

**Comment by mcdaij** [comment]
Sorry, assumed the total earnings page wasn't finalized. Just pushed with it added.

**Comment by billuraksoy** [comment]
Please add "survey" and "summary" pages. They are on pages 14 and 15 in this document. 
[Multiple TPGG Instructions_7_17.docx](https://github.com/billuraksoy/virtual_lab/files/5023665/Multiple.TPGG.Instructions_7_17.docx)

**Comment by mcdaij** [comment]
Added both of these

**Comment by billuraksoy** [comment]
@mcdaij  Please add these two pages right after the "Contributions game - Total Earnings page" and before the experiment starts. 
[question page.docx](https://github.com/billuraksoy/virtual_lab/files/5086012/question.page.docx)

**Comment by mcdaij** [comment]
Added.

**Comment by mcdaij** [comment]
Pushed the dependancy.

**Comment by mcdaij** [comment]
So just to make sure you're aware of this, as is coded right now, the answers and the error checking on the questions page aren't dependent on the thresholds and payouts, so if you want that to work for other treatments they're going to have to have more logic implemented.

**Comment by billuraksoy** [comment]
I will close this an open another issue for this.
