### ISSUE TITLE
SVO does not start with Decision 1

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#100]
In my test, 2 subjects dropped, 2 subjects left the study because of that, I completed part 1 with 2 subjects.
One of these subjects started SVO with Decision 5, and the other started with Decision 6. 
Everyone should make all 15 decisions.

**Comment by mcdaij** [comment]
The SVO code all exists on one page so they have a cookie script set up to tag your browser as you are going through it, and return you to the same page if you disconnect, leave and come back, or simply refresh. This occurs across all instances of the same game in the same browser, so it doesn't matter which participant you are, as long as you're accessing from the same place it will cookie you and bring you back to your saved progress. To avoid this either turn off cookies temporarily, disable them for the site, or just use a private browsing window (incognito mode on chrome, inprivate on firefox, etc.).

Note: this shouldn't affect testing unless you have multiple participants from the same computer (and any of them don't finish).
