### ISSUE TITLE
browser settings for subjects

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#102]
Hi Jack,

We have the experiment scheduled for Thursday. We will have about 40 subjects, all using their own computers. I think I should provide some information regarding their browser settings etc to increase the performance of the code and also decrease the prob of getting errors etc. 
Which browser should they be using? Does it matter? Also, do they need to make any changes to their browser settings? e.g. allow cookies. 
Anything else I should include in my recruitment message in terms of the technology they are using?

**Comment by mcdaij** [comment]
Browser and settings shouldn't matter, this should be relatively hardware agnostic, but to be safe I'll test with all the browsers I have to hand and get back to you.

**Comment by mcdaij** [comment]
Tested on Chrome, Opera, Firefox, IE, Edge,  and Safari (on mobile). Everything except for Internet Explorer worked flawlessly. Internet explorer refused to display the delayed_next button no matter what I did. Bottom line: pretty much any modern browser should do fine, except for IE, Chrome is recommended.
