### ISSUE TITLE
edits all_vars

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#103]
Following variables should be recorded in participant vars (all_vars):

*subject id info to be able to match other info which is not recorded in in all_vars:
participant.id_in_session 
participant.code 
participant.label

*GameOverview-attention_check_2

*Practice Round:
computer's contribution to a
computer's contribution to b

*for each round (currently it looks like it is only recording subjects' own contribution to each of the accounts):
player.id_in_group (i.e. the order of play)
group id in subsession (i.e. group ID)
player.acc_a_total
player.acc_b_total
player.thresh_a_met
player.thresh_b_met
player.payoff

*Also these from the SVO game: (If it is not too hard to code, it is ok to leave them out if it is complicated to save them here)
svo.1.player.svo_angle
svo.1.player.alpha
svo.1.player.svo_type
svo.1.player.inequality_aversion_score

*And the earnings variables: earnings from Part 1 in USD, earnings from Part 2 in USD and total earnings in USD (excluding the base payment of 5 USD) (again, if it is too complicated to code, you can leave it out, but please make sure that this is saved in the data set)

These should be excluded:
Question-question1-1
Question-question2-1
Question-question3-1

**Comment by mcdaij** [comment]
For the practice round that is already saved as practiceA and practiceB.

The svo vars are also saved as well, though only after svo completes because that's when they're calculated. 

Also, for the Question-question1-1 through 3, that is saved by the json dump code to a separate participant var that is recorded at the end, #33 if you want me to remove it then those will not be accessible through the json dump. (If you really do want me to remove them it's just one line of code to comment out so just let me know.)

**Comment by billuraksoy** [comment]
It is ok, I dont need those variables to be saved, but it wont be an issue if they are saved in here.

**Comment by billuraksoy** [comment]
@mcdaij I just tested the code and I do not see this issue as fixed. 
This is the current list:

**Comment by mcdaij** [comment]
That's just the vars_json_dump participant variable, not all_vars, all_vars is all of the participant vars passed in to every page so you can see them for debug, if you'd like the specified variables saved to the json dump that's doable, but I just tested it on the heroku and the other vars are getting saved to all_vars.

**Comment by billuraksoy** [comment]
ok gotcha ! My bad, I thought those two were the same. Sorry about that miscommunication. I actually need all of the variables listed in this issue to be saved in vars_json_dump. This is because I need those variables for data analysis and it is quite hard to clean the data because of the way orsee saves them. By saving those variables here, makes the cleaning process much easier:  threshold_public_goods_end.1.player.participant_vars 
Once you are done with the other few issues that I had opened today, please merge the testing branch with master. And then you should again keep working on a testing branch. This way, I can also test the master branch while you work on this. Thanks very much.

**Comment by billuraksoy** [comment]
It looks like it is not saving the variables for all rounds of the game, but just the first round.

{"Informed_Consent-consent-1": "False", "id_in_session": 1, "code": "g0kj0gbn", "label": null, "GameOverview-attention_check_1-1": "0", "GameOverview2-attention_check_2-1": "0", "Question-question1-1": "0", "Question-question2-1": "0", "Question-question3-1": "0", "Game-pr_contribution_acc_a-1": "2", "Game-pr_contribution_acc_b-1": "1", "PracticeGame-computer_con_A": 4, "PracticeGame-computer_con_B": 0, "**Game-contribution_acc_a-1": "5.00 tokens", "Game-contribution_acc_b-1": "0.00 tokens", "Game-id_in_group-1": 1, "Game-_id_in_subsesion-1": 3, "Game-acc_a_total-1": 5, "Game-acc_b_total-1": 5, "Game-thresh_a_met-1": false, "Game-thresh_b_met-1": false, "Game-payoff-1": 0,** "Play-input_self_1-1": "8.50", "Play-input_other_1-1": "6.80", "Play-input_self_2-1": "8.70", "Play-input_other_2-1": "2.00", "Play-input_self_3-1": "5.00", "Play-input_other_3-1": "10.00", "Play-input_self_4-1": "5.30", "Play-input_other_4-1": "9.30", "Play-input_self_5-1": "10.00", "Play-input_other_5-1": "5.00", "Play-input_self_6-1": "9.90", "Play-input_other_6-1": "5.30", "Play-input_self_7-1": "9.00", "Play-input_other_7-1": "6.70", "Play-input_self_8-1": "9.40", "Play-input_other_8-1": "9.60", "Play-input_self_9-1": "10.00", "Play-input_other_9-1": "7.00", "Play-input_self_10-1": "10.00", "Play-input_other_10-1": "7.00", "Play-input_self_11-1": "7.60", "Play-input_other_11-1": "9.40", "Play-input_self_12-1": "6.70", "Play-input_other_12-1": "9.70", "Play-input_self_13-1": "5.80", "Play-input_other_13-1": "9.20", "Play-input_self_14-1": "9.30", "Play-input_other_14-1": "9.30", "Play-input_self_15-1": "9.20", "Play-input_other_15-1": "9.00", "SVO-svo_angle": 25.769327624338718, "SVO-alpha": 0.48275862068965514, "SVO-svo_type": "Prosocial", "SVO-inequality_aversion_score": 0.4653493016340668, "Survey-birth_year-1": "0", "Survey-gender-1": "0", "Survey-income-1": "0", "Survey-Wh-1": "False", "Survey-Bl-1": "False", "Survey-Na-1": "False", "Survey-As-1": "False", "Survey-Nh-1": "False", "Survey-Hi-1": "False", "Survey-Me-1": "False", "Survey-OtherBool-1": "False", "Survey-other-1": "", "Survey-risk-1": "0", "Paypal-paypal-1": "", "Paypal-venmo-1": "", "Survey2-new_understanding-1": "0", "Survey2-strategy-1": "", "Survey2-anything_else-1": "", "Part1Earnings": 10.0, "Part2Earnings": 0.0, "TotalEarnings": 15.0}

**Comment by mcdaij** [comment]
This is from round 4 run from Heroku, I'm not able to replicate the problem you're having.
{'timed_out': False, 'groupmate_timed_out': False, 'vars_json_dump': {'Informed_Consent-consent-1': 'False', 'id_in_session': 1, 'code': 'cyxpi71b', 'label': None, 'GameOverview-attention_check_1-1': '0', 'GameOverview2-attention_check_2-1': '0', 'Question-question1-1': '0', 'Question-question2-1': '0', 'Question-question3-1': '0', 'Game-pr_contribution_acc_a-1': '0', 'Game-pr_contribution_acc_b-1': '0', 'PracticeGame-computer_con_A': 3, 'PracticeGame-computer_con_B': 0, 'Game-contribution_acc_a-1': '0', 'Game-contribution_acc_b-1': '0', 'Game-id_in_group-1': 1, 'Game-_id_in_subsesion-1': 1, 'Game-acc_a_total-1': 1, 'Game-acc_b_total-1': 0, 'Game-thresh_a_met-1': False, 'Game-thresh_b_met-1': False, 'Game-payoff-1': 5, 'Game-contribution_acc_a-2': '2', 'Game-contribution_acc_b-2': '0', 'Game-id_in_group-2': 1, 'Game-_id_in_subsesion-2': 1, 'Game-acc_a_total-2': 4, 'Game-acc_b_total-2': 0, 'Game-thresh_a_met-2': False, 'Game-thresh_b_met-2': False, 'Game-payoff-2': 3, 'Game-contribution_acc_a-3': '0', 'Game-contribution_acc_b-3': '0', 'Game-id_in_group-3': 1, 'Game-_id_in_subsesion-3': 1, 'Game-acc_a_total-3': 0, 'Game-acc_b_total-3': 0, 'Game-thresh_a_met-3': False, 'Game-thresh_b_met-3': False, 'Game-payoff-3': 5, 'Game-contribution_acc_a-4': '0', 'Game-contribution_acc_b-4': '0', 'Game-id_in_group-4': 2, 'Game-_id_in_subsesion-4': 1, 'Game-acc_a_total-4': 0, 'Game-acc_b_total-4': 0, 'Game-thresh_a_met-4': False, 'Game-thresh_b_met-4': False, 'Game-payoff-4': 5}, 'practiceA': 3, 'practiceB': 0, 'timed_out_round': 0}
