### ISSUE TITLE
summary page issue

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#104]
I had this error on the summary page. I forgot about the cookie situation for SVO so some testing subjects did not make decisions for some of the SVO questions. Is this why this happened? Just making sure that this is not due to something else. 

I will test again and let you know if this re-occurs. 

![Screen Shot 2020-10-11 at 10 38 36 AM](https://user-images.githubusercontent.com/44884690/95681449-ed18b800-0bad-11eb-835b-3d85f4f858cd.png)

**Comment by billuraksoy** [comment]
I tested the code with 2 participants (one with incognito) and I got the same error page:
![Uploading Screen Shot 2020-10-11 at 1.39.20 PM.png…]()

**Comment by mcdaij** [comment]
Yeah, somehow the cookies carry over, even in incognito mode. I've been looking in to a fix but I haven't found much yet. Although, as of the last push I did, this specific problem is fixed.
