### ISSUE TITLE
error in Part 2 Earnings

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#108]
There seems to be multiple issues here.

1. The conversation rate is wrong. In this example, 19*0.3 = 5.70
![Screen Shot 2020-10-12 at 6 15 20 PM](https://user-images.githubusercontent.com/44884690/95794856-e3c74280-0cb6-11eb-8bcb-418da2d9ae13.png)

2. For this subject, the code is not pulling the numbers correctly. 
![Screen Shot 2020-10-12 at 6 16 00 PM](https://user-images.githubusercontent.com/44884690/95794902-fc375d00-0cb6-11eb-86bb-35582ccfd491.png)

**Comment by mcdaij** [comment]
The first part was just printing to too few decimals earlier on which made it look like it was doing the math wrong.

I'm not sure how the second part happened, I'd assume it was a database issue or an issue with the way svo was filled out, either way I can't seem to replicate it. If you could include the all_vars printout in the screenshots when posting bugs that would be a huge help.

**Comment by billuraksoy** [comment]
I had the screen open so could take a screenshot. Let me know if this helps. 

![Screen Shot 2020-10-13 at 8 32 51 AM](https://user-images.githubusercontent.com/44884690/95860898-af8f6880-0d2e-11eb-97ab-37f7ef8b5a54.png)

**Comment by billuraksoy** [comment]
I tested the code and everything seems to be calculating correctly. 
I think some of the problems were caused because I was using the same computer for different subjects. I did this last testing with 4 different computers and I have not seen any issues. I have not checked the data excel sheet. I will examine the data and will open more issues if there are any. Thanks Jack!
