### ISSUE TITLE
Text corrections

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#11]
1- Overview/3/ : 
Please underline this part "does not employ deception"

2- Rules/4/: Is says "You will play the contribution game for {Constants.total_rounds}} rounds." 

3- GameOverview/5/ : please make this bold: "However, in each round, you will randomly be re-matched with 2 other participants."

4- GameOverview2/6/ : 
*please remove the line after "group Account A" subtitle 
*please remove the line after "Group Account B" subtitle 
*please add  a line **before** "Group Account B" subtitle 
* Please update this sentence "The threshold for Group Account A is at least 60 tokens." and remove "at least". 
* Please update this sentence "The threshold for Group Account B is at least 20 tokens." and remove "at least". 

5- Results page: 
Please update "points" with "tokens". 

5- On the contribution screen, you indicate how many tokens they would like to contribute. Can you update "points" into "tokens".

**Comment by mcdaij** [comment]
Sorry, just wanted to get a beta version in that had all of the necessary features. Just pushed the cosmetic tweaks and the text change will be in shortly.

**Comment by mcdaij** [comment]
Finished the text changes, will leave this ticket open in case you have any further changes you'd like to make, but feel free to close it if you like.

**Comment by billuraksoy** [comment]
No need to say, sorry. The code looks pretty good. Thanks for the edits. I will close this after I test it again.
