### ISSUE TITLE
branch conflict

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#110]
I had made some text edits on the testing branch, but after your latest push, there is an issue with the branches now. Can you please fix it?

**Comment by mcdaij** [comment]
Sorry for the late reply, but just go ahead and overwrite the testing branch and I'll take care of it.

**Comment by billuraksoy** [comment]
It looks like you solved this issue. I am closing it. 
![Screen Shot 2020-10-13 at 8 14 54 AM](https://user-images.githubusercontent.com/44884690/95859164-30009a00-0d2c-11eb-83ab-bef13a2716c1.png)
