### ISSUE TITLE
decision timer

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#115]
Can you please change the default decision timer to 60 seconds (currently 30). This change applies to all four treatments. 
I assume that this is a very minor change and you can directly make it to the master branch. Please let me know when done. 
I will test the master branch one last time and close this issue. 

Thanks very much Jack. I do appreciate you working around the clock for this project. I hope your exam went well!

**Comment by mcdaij** [comment]
It's no problem! Thanks!
