### ISSUE TITLE
minor change on payment info page

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#116]
Our lab director mentioned that doing the payments with Venmo, we need both username and phone number. Can you please make the following on this payment info page. 

This is not terribly urgent, by Sunday morning will be fine. 

Updated Text:

You will receive your earnings via PayPal or Venmo. If you want to be paid via Paypal, provide the email address associated with your PayPal account. If you want to be paid via Venmo, you have to provide both your username and the phone number associated with your Venmo account. 

You are responsible to provide the correct information. If your information is not correct, you may not receive your earnings.

PayPal Email Address:

Venmo Username:

Venmo Phone Number:

[you do not need to make any changes to the next button-the current setting should be fine]

**Comment by mcdaij** [comment]
Pushed to testing, this will require a database reset.
