### ISSUE TITLE
threshold_public_goods_game.10.player.id_in_group bug

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#119]
I examined the data and this is what I see. When the subject timed out in period9, in period 10, it looks like subjects were reassigned player.id_in_group values instead of keeping the same one. This is how subjects' roles got switched which should not have happened. 

Second thing I noticed is that the subject who timed out also received a number in svo.1.player.id_in_group.
I am not sure if this might have caused issues though. 

I will email this data to you.

**Comment by mcdaij** [comment]
This was a grouping error on otree's end. After rereading the source code, when you specify "fixed_id_in_group" in the _group_randomly function, instead of actually grouping based on the player class's current id_in_group, it groups based on the order in which it is presented players objects. This was a relatively easy fix once I figured out what was actually causing the problem.

**Comment by billuraksoy** [comment]
I quickly tested the sequential treatment and it looked good. Quick questions: 

1)Can you tell me which variable shows me who is the first mover and who is the second mover? 
2 Just to be sure, can you tell me what these variables mean? 
player.id_in_group 
group.id_in_subsession

**Comment by mcdaij** [comment]
1) 
player.id_in_group shows who moves first (but only during the proper game). This is determined by (player.id_in_group - 1) modulus divided by the group size. 
2)
player.id_in_group is the numerical id for the player in the group, if they're the first mover it will be 1 if they're the second it will be 2.
group.id_in_subsession is the numerical id for the group of players as listed in the subsession, so two people would be in group 1, two in group 2 and so on.

**Comment by billuraksoy** [comment]
With your fix, in a given session, player.id_in_group will stay fixed across all rounds? So the roles will stay fixed, right?

**Comment by mcdaij** [comment]
Yes, sorry. The code manually sorts players by their role and ensures they're given the same role the next round.
