### ISSUE TITLE
New parameters

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#12]
Would you please update the code with these parameters:

group_size=2
threshold_high = 10
threshold_low = 6
value_high = 10
value_low = 7
endowment = 5 (I did not specify this as a parameter before, sorry about that. It was 20 tokens previously. It needs to be 5 now. Also, the text will need to be updated. )

They can now give in increments of 1. (instead of 10).
Thank you!

**Comment by mcdaij** [comment]
Reworked for these, (sorry about setting it to 1 before pushing, I was testing the later survey stuff and making it one person per group let me test it faster and I must have forgot to change it back before pushing)
