### ISSUE TITLE
data column order

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#121]
In some of the sessions, the data points were recorded in different columns (like the order of columns were randomized in a way). I noticed this when I appended all sessions into one excel sheet. 
As far as I can tell, this was the case for session config variables. Do you know why this might have happened?

**Comment by mcdaij** [comment]
I'm not sure what you mean, can you send me the data?

**Comment by mcdaij** [comment]
wait sorry, never mind.

**Comment by mcdaij** [comment]
Okay after looking through the data you sent me I'm still not sure what you mean.

**Comment by billuraksoy** [comment]
sorry, I should have been clearer. I sent you another data set (combo of two sessions). Let me know if you still have questions about the issue.

**Comment by mcdaij** [comment]
This was just an issue with the way the settings were ordered given the treatment. This did not have any effect on the data (other than the setting order).
