### ISSUE TITLE
text edit

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#124]
On the understandings question page (mtpg/Question), can you please make this text edit to the second paragraph:

Current: Suppose that **your** group members contributed a total of 0 tokens to Group Account A and a total of 5 tokens to Group Account B. 

Suggested: Suppose that the other two group members contributed a total of 0 tokens to Group Account A and a total of 5 tokens to Group Account B.

**Comment by mcdaij** [comment]
Is the two person group still fine with "Suppose that your group member contributed"?

**Comment by billuraksoy** [comment]
The two person group one is fine. Thanks for checking.
