### ISSUE TITLE
matching issue 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#18]
There is an issue with the game. I openned the game with two participants. On one of the screens, I received the following error message before I saw the decision screen. 
On the second one, it proceeded to the decision screen without an issue. 

FYI: Earlier today, I made a change in the code to fix an error that I was getting. It is the "Update models.py" commit. 

![Screen Shot 2020-08-14 at 11 57 44 AM](https://user-images.githubusercontent.com/44884690/90268657-5fc31c80-de25-11ea-8b67-bd20eb86ddd0.png)

**Comment by mcdaij** [comment]
The problem wasn't in the way the matching was being done, I had just set the lower limit variable to 1 for testing purposes, so when you moved the group size back to 2 it still thought it was supposed to start making the groups once anyone joined, but it was trying to make a group of 2 with only one person on. Updated the var.
