### ISSUE TITLE
round summary page edits

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#20]
Please make the following edits on round summary page:

1- your earnings box will appear on top instead of at the bottom. 
2- remove "points" from all boxes
3- Remove the lines that say "you earned x tokens from Group Account A/B"
4- Update and Bold "Threshold is met" and "Threshold is not met" - also please underline "not"
5- in each of the group account boxes, present the threshold and earnings if threshold is met sections in gray scale. I visualized it here: 
![Screen Shot 2020-08-14 at 4 38 34 PM](https://user-images.githubusercontent.com/44884690/90290838-995b4e00-de4c-11ea-9d74-2c47306924ec.png)

**Comment by mcdaij** [comment]
Finished and pushed all 5 items.
