### ISSUE TITLE
paypal question in survey

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#23]
Please add this question at the end of the survey:
Thank you for completing this study. You will receive all of your payment via paypal. Please enter the email address or phone number that is connected to your paypal account. Please note that you are responsible to provide the correct information. If your information is not correct, you may not receive your earnings.

**Comment by mcdaij** [comment]
Should this be on a separate page?

**Comment by billuraksoy** [comment]
separate page would be good.
