### ISSUE TITLE
participation payment variable

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#26]
Can you please create a new variable: participation_payment and update the code whenever we need this. 
The places that we currently use:
-overview page
-summary page

You will also need to update the total earnings using this new variable instead of a parameter value. 
For now, lets set participation_payment=4

**Comment by mcdaij** [comment]
Pushed.

**Comment by billuraksoy** [comment]
I had not realized that it was possible before but i think it may be more efficient for us to close these issues whenever you push the corresponding change in the code. So when you push changes, connect that with the corresponding issues and close the issues that way. @mcdaij  Would that work?

**Comment by mcdaij** [comment]
Yes that would work, I'll do that going forward.

**Comment by mcdaij** [comment]
(as it is set up right now it only closes the issue when its pushed to main not testing)

**Comment by billuraksoy** [comment]
That is fine. Thanks for letting me know.
