### ISSUE TITLE
treatments and session config variables

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#27]
Jack, Once you are done with other issues, it is time to start incorporating our treatments. In this experiment, we will have four treatments (2x2 design -which means we have two factors in the design. Factor 1: Simultaneous vs sequential; factor 2: large difference vs small difference. This 2x2 design results in 4 treatments. The current version is the simultaneous large difference treatment. We will also have simultaneous small difference, sequential large difference and sequential small difference treatments. 

We will work on the sequential treatment soon. For now, you can easily code the small difference factor and indicate which variables may change between small and large difference treatment. 

In the large difference treatment we have the following variables:
threshold_high=10
value_high=10
threshold_low=6
value_low=7

In the small difference treatment, we have the following variables (for now, the only difference is the threshold_high value, but we may play with other variables in the future that is why I would like to include all 4 in each factor): 
threshold_high=8
value_high=10
threshold_low=6
value_low=7

Here are my suggested session level variables that I should be able to customize on the admin page:

**participation_payment** (this is also mentioned in #26 ) 
**large_difference_treatment** (=1 the game is large difference if 0, it is small diff)
**simultaneous** (=1 if it is simultaneous treatment, =0 if sequential)
**decision_timer** (this is the timer on decision pages, currently I think it is 30 seconds)
**total_rounds** (currently is is 10, but I should be able to update it here)
**synchronous_game** (this is related to #9 )=1 then all subjects move together, =0 then there is a lower_limit set as discussed in the original instructions. 

There is some help provided here:
Treatment documentation: https://otree.readthedocs.io/en/latest/treatments.html
Session config documentation: https://otree.readthedocs.io/en/latest/treatments.html#configure-sessions

This is a very long issue and I hope it is clear. If not, I am happy to discuss this over zoom.

**Comment by mcdaij** [comment]
Added some dummy variables for this because hooking this in retroactively would be more difficult than building it around this concept from the start.

**Comment by mcdaij** [comment]
Finished the system for this (haven't coded any of the other treatments but that should be the easy part). It shows a few too many variables in the admin console, hope that's not a problem.
