### ISSUE TITLE
sequential treatment transition and decision pages

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#30]
Here are the pages that we will use in the sequential treatment. Please notice that these pages also exist in the simultaneous treatment (except the waiting screen for the second mover which is new). Instead of creating new pages, create conditional statements such that depending on the treatment, certain paragraphs/texts are shown to the subjects. 

[sequential treatment instructions.docx](https://github.com/billuraksoy/virtual_lab/files/5119349/sequential.treatment.instructions.docx)

**Comment by billuraksoy** [comment]
I will update these screenshots based on the edits we did to the simultaneous case. I will provide page suggestions here soon.

**Comment by billuraksoy** [comment]
Updated screens for sequential treatment

[sequential.treatment.instructions.docx](https://github.com/billuraksoy/virtual_lab/files/5152102/sequential.treatment.instructions.docx)

**Comment by billuraksoy** [comment]
Take a look at #57 before you start coding this treatment. We will have to fix #57 for the actual experiment so it may be helpful for you to know before you start coding this one.

**Comment by mcdaij** [comment]
Just pushed this implementation (same push as the one that closes #61)
