### ISSUE TITLE
url name

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#32]
currently, when I am testing the url has "threshold_public_goods" in it: 
https://rpi-virtual-lab-testing.herokuapp.com/p/5lneaqk0/**threshold_public_goods**/Informed_Consent/1/

can you please change it to : mtpg ?

**Comment by mcdaij** [comment]
Currently there's four apps its using: threshold_public_goods (the introduction), threshold_public_goods_game (the actual game), threshold_public_goods_end (the results debrief and follow up), and timeout (the app it sends players to to get them out of the groupmaking pool). The url is echoing the app names. Would you like me to rename all the apps or just the intro?

**Comment by billuraksoy** [comment]
all of them please. The idea is that I do not want subjects to know that this game is called a threshold public goods game. We try to use a more neutral language (such as group account instead of a public good) in the experiments. This way, people will not be biased by their beliefs/values/thoughts/prior experiences etc.
