### ISSUE TITLE
Saving the player variable as a participant variable on each page.

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#33]
Jack, can you please update the code such that it saves the player variables as participant variables on each page. This makes testing more efficient. 

@ianchadd has this code and he will point you to the right direction. 

_Please do this only after all of the simultaneous alpha milestone issues are all closed._

**Comment by ianchadd** [comment]
Hi Jack, 

We have some code for this in the other repo (rpi_3208). See models.py for the app survey_demographics_qsp where I've defined participant_vars_dump in the Player class. The function is called on each page in pages.py.

Depending on how Dr. Aksoy wants data to be organized, it might be helpful to also look at the code for the app prolific_id_end, which takes all participant variables saved up to that point and json dumps them into a player variable (which I've found to be easier for data analysis later).

**Comment by billuraksoy** [comment]
I am closing this issue. For now, this is very important for this study.

**Comment by billuraksoy** [comment]
I actually realized that this is an important feature for data analysis. So I am reopening this. Can you please follow Dr. Chadd's suggestion and edit the code?

**Comment by billuraksoy** [comment]
Lets talk about how to save these.
