### ISSUE TITLE
Understanding Questions: Error Messages and Answers

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#34]
Jack mentioned -refering to the understandings questions and their error messages: "So just to make sure you're aware of this, as is coded right now, the answers and the error checking on the questions page aren't dependent on the thresholds and payouts, so if you want that to work for other treatments they're going to have to have more logic implemented."

After the code is finalized with all treatments, please include this logic into the answers and error messages.

**Comment by mcdaij** [comment]
This will not adapt to variable group size, but it should work for any reasonable combination of thresholds and payouts. Group B always pays out, group A never does, and you are (almost) always left with at least one token left over unallocated.
