### ISSUE TITLE
minor edits

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#41]
Once you finish all high priority edits that we discussed earlier today, can you please make the suggested edits mentioned in the comments on each page? Feel free to make executive decisions for text etc. I will go over the code once you are done and can make further text edits if needed. Thank you. 
[Otree Screenshots_2.docx](https://github.com/billuraksoy/virtual_lab/files/5144176/Otree.Screenshots_2.docx)

**Comment by mcdaij** [comment]
(that was an accident, sorry!)

**Comment by mcdaij** [comment]
On page 7 one of the comments is "Make ethnicity question multiple choice" do you mean make it a checkbox instead of a radio button?

**Comment by billuraksoy** [comment]
Yes, checkbox, sorry about that.
