### ISSUE TITLE
Push all tutorial code to this repo and synch with Heroku

### ISSUE THREAD

**Issue by ianchadd** [billuraksoy/virtual_lab#5]
- [x] Create a "testing" branch in this repo
- [x] Create a "testing" branch in your local clone of the repo
- [x] Push all of your code from the oTree tutorials (likely in a local directory called "oTree") to the testing branch of this repo
- [x] On Heroku (app name to be added to this Issue shortly), set up automatic deployment of the "testing" branch
- [x] Test to make sure that "Testing" branch code is accessible from Heroku app website

**Comment by ianchadd** [comment]
only complete this Issue once you are done with all of the oTree tutorials

**Comment by ianchadd** [comment]
**Note:** when doing anything with Heroku, do not change anything about the Dynos (including changing the subscription plan). These apps have been set up only recently and it's possible that you have "permission" from Heroku to change those plans as a collaborator, but do not do so.

**Comment by ianchadd** [comment]
Also note: the Heroku app that needs automatic deployment set up is "rpi-virtual-lab-testing", owned by Dr. Aksoy

**Comment by mcdaij** [comment]
Sorry about the delay there, tried a bunch of deploy steps and couldn't figure out what was wrong, eventually I just tried taking it out of the folder I had put it in, turns out that was what had been breaking everything.
