### ISSUE TITLE
Participate in fake experiment

### ISSUE THREAD

**Issue by ianchadd** [billuraksoy/virtual_lab#6]
To see the interface:
1. Follow this link: https://rpi-3208-testing.herokuapp.com/join/gopr9uka0j/
	Note: the server is currently set up so that this link can only be followed up to 10 times (it limits the number of subjects who can participate). So if you end up needing to start the experiment more times than that, let me know and I can send you a new link. Also, please send me an email to let me know whenever you are finished with the interface (so that I can push code that I am working on today to this repo and reset the database). 

2. Use "Wuwuwuwuwuwuwuwuwuwuwuwu" for the "Prolific ID" when prompted. We use https://www.prolific.co/ as an online recruitment platform for these experiments and all economics experiments that we run will require subjects to input their IDs from that website. For testing, it's fine to use any 26-character string, but this is the one I use (and have saved in a sticky on my machine for testing).

3. At the end, you will be prompted to click on a link to "Return to Prolific", which will not work. This isn't a bug - we can talk more about that feature of all of our experiments later.

**Comment by mcdaij** [comment]
Finished and looked at the internal structure a bit to see how it ticks.
