### ISSUE TITLE
decision_order variable 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#64]
I tested the code and checked the data. I think we are missing a variable that tells me who went first and who went second in each group. 

There is this variable: threshold_public_goods_game.1.player.id_in_group 
At first, I thought this variable showed which group member was the first mover and which one was the second mover. But I dont think so. Right? 

Summary: do we have a variable that saves the order of the play? If yes, please comment its name here. If not, please create a new variable (decision_order) and have it record this data for each group.

**Comment by mcdaij** [comment]
id_in_group is the variable that determines turn order.
