### ISSUE TITLE
text edits on "please note" pages

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#69]
on the "please note" page, the following texts at the beginning of the first paragraph should be deleted:
_first mover._
_second mover._ 

![image](https://user-images.githubusercontent.com/44884690/92532185-bdb50b00-f1fd-11ea-8929-3490515ed814.png)

**Comment by mcdaij** [comment]
This was just a glitch, it was missing the first part of the sentence.
