### ISSUE TITLE
threshold_public_goods_end.1.player.round_chosen_for_payment does not record correctly

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#71]
This variable is recording wrong. 
More specially, it records: "random round" - 1 .  For example, if the randomly chosen round is 1 (as shown to subjects), it is recorded here as 0. The payoff etc. calculations that are based on this randomly chosen round are all correct (i.e. all calculations are based on the fact that 1 is the chosen round even though it says 0 in this variable. )

**Comment by mcdaij** [comment]
It was being recorded as 0 because that's actually how the data is being accessed, round 1 is the 0th round in the data storage so the first round is actually 0 on the backend, regardless, I just pushed a minor fix to record it as the actual round number.
