### ISSUE TITLE
practice round

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#81]
We would like to add a practice round for all treatments. The idea is that the subjects will play this practice round before the actual experiment to have a better understanding of how the game works ( and in case of sequential treatment, understand how their role works)

1. add a page after the "warning" page (which is the last page in the instructions before the game starts). This page will inform them about the practice round, say something like "before the actual game starts, we would you like to participate in a practice round. This will help you get familiar with how the game works". It can have a title of "Practice Round". I can edit this page later. It should have a button "Start Practice Round". 

2. They play one round of the game. The game depends on which treatment they are in and what role they have. so it needs to be different for each treatment and role. The earnings in this practice round is recorded but it will not impact their earnings from the study. 
This practice round should be the exact same game that they will play. More specially: 
In simultaneous treatment: they make a decision without knowing what the other person contributed, and they see the round summary page. 
In sequential: if they are the first mover, they make the decision first, and then they see the summary page. 
If they are the second mover: they observe the decision made by the first mover, make their own decision, and then see the summary page. 

3. The round summary page is the same page as the actual game. However, it should make it clear that this is a practice round and they will not be paid for their earnings in the practice round. 

4. Add a transition page that comes after the practice round summary page and before the actual experiment starts. 
title: "You are now ready to start the game". 
Body: "You completed the practice round. Now the game will start. Please click "Start" whenever you are ready. Remember, you will have x seconds to submit your decisions. "

5. We can discuss this and do whatever is easiest for you. I am thinking that they can play this practice round against the computer. Basically, the computer makes a random decision as the group member. If this is not easy to code, they can play the practice round with one another.

Please think about this practice round structure from a programming perspective, and lets discuss this over zoom. Please send me an email to set up a meeting time once you read this issue.

**Comment by mcdaij** [comment]
I thought it would be best to remove the warning page and the secondary wait page to help with app flow, because it was a little bit confusing to be told "you're about to start the game" on the warning page, and then immediately go into a practice round. (All I have to do to add it back if you'd prefer is uncomment one line of code, so if you'd like it back I can have it pushed in 30 seconds) Otherwise, and other than anything I missed, this should be fully in.
