### ISSUE TITLE
heroku error - constants.players_per_group cannot be 1

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#82]
I am trying to reset the database in heroku and this is what I got:

![Screen Shot 2020-09-29 at 10 22 54 AM](https://user-images.githubusercontent.com/44884690/94571222-bce02980-023d-11eb-8ef8-dc37124327d7.png)

**Comment by billuraksoy** [comment]
It seems to be working now with this fix. However the django warning is still there. this will not create any issues with data collection right?

**Comment by mcdaij** [comment]
I don't see this on the Heroku dyno anymore, regardless, I set it to None so the error shouldn't show up anymore. As long as the site is working it should be collecting data (although the Heroku database does appear to be low on space, and if it runs out, even if it's in the middle of an experiment, it will not allow more inputs).

**Comment by billuraksoy** [comment]
Where can I see that heroku database is low on space? How can I increase that? Does it reset overtime I reset the database?

**Comment by mcdaij** [comment]
It just gave me a pop up notification, I'm not sure.
