### ISSUE TITLE
Coding waiting_room_lowerlimit in two alternative ways

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#9]
Can you please code the experiment such that we have two alternative ways for how the waiting rooms/random rematching works.

1. This is what I described in the instructions. Whenever waiting_room_lowerlimit has been reached in each corresponding waiting room, subjects are matched randomly. 

2. Subjects start the experiment at the same time. And they all move across rounds at the same time. Thus waiting room lowerlimit will be equal to the number of subjects in that session. Unfortunately, we will not know how many subjects we will have before the experiment starts. Thus the code needs to update based on how many people entered the session. 
If someone drops out of the study (times out), then the computer will randomly make decisions for them. If this happens, this information is revealed to the subjects on their round summary page. The number of computers making decisions this way is determined by 1- number of active subjects 2-group size. If any given point, the number of active subjects is not divisible by the group size, then the computer will fill that in. Currently, we have groups of 2. If one subject drops out, then computer makes a random decisions  as a group member. In order to complete the study, we will need to match one of the participants with the computer for the rest of the experiment. Unless another person drops out. In that case, the total number of subjects would be a multiple of 2 again and the computer is not needed any longer. This should be coded such that it automatically adjusts when we change the group size. 

Please let me know if you have any questions.

**Comment by billuraksoy** [comment]
@mcdaij  Once we finalize all other issues, lets discuss this over zoom. I will send an email to set a time.

**Comment by billuraksoy** [comment]
We need the second method to be coded for the pilot on Monday. I think this is the biggest main issue left. Thanks for other edits. 
We create a link and share that link with actual subjects. That link may be different that the links that we use for testing. I am not sure. I will talk to Dr. Chadd about running the study live with actual subjects, how to set things up, which link to use etc. Would that have an impact on how you should be coding this?

**Comment by billuraksoy** [comment]
I learned this from Dr. Chadd: N = len(self.get_players())
He said we can define this at the group, page, subsession level etc. and we can get this updated at the end of each round. I think this will solve the issue. 

Without knowing the itty bitty details of the code this is what I think as a solution: 
define N at the beginning of the study to get the total number of subjects participating in the experiment in that session (remember subjects may not join the study simultaneously, there may be a few min diff),
and then update N on the round summary page in each round. Using this updated N, update the waiting_room_lowerlimit  variable. 

Again, the goal is: 
1-To make sure that all subjects start Round 1 all at the same time
2- All subjects start each consequent round at the same time
3- if any subject drops out, rest can still continue.

**Comment by mcdaij** [comment]
Good suggestion, that's very close to the way it's already written.

**Comment by billuraksoy** [comment]
This is done. We do not need the other coding method for now so I am closing it.
