### ISSUE TITLE
SVO -transition page

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#94]
I made edits to the instructions such that the contribution game is now Part 1 and SVO will be Part 2 of the study. 

After the subjects complete all rounds of the contribution game, they should move the SVO app and see the following page and then move to the SVO game. I will open another issue for SVO related changes (and describe the changes to the earnings structure etc.)

{% block title %}
    PART 2 - Instructions 
{% endblock %}

{% block content %}

Thanks for completing Part 1 of this study.

 In Part 2, we will again be trading in tokens. However, we will use the following conversion rate for Part 2: <b>1 token = 0.30 USD.</b> <br><br>

 In this part of the study, you have been randomly paired with another participant whom we will refer to as "Other person". <br><br>

 You will be asked to make 15 decision about allocating tokens between yourself and this other person. For each of the following decisions, please indicate which allocation you prefer the most. <br><br>

At the end, one of these allocation decisions will be randomly selected to be payoff relevant and we will pay you as well as the other person based on your decisions. <br><br>
 
	{% delayed_next wait=22000 %}

{% endblock %}

**Comment by mcdaij** [comment]
Sorry, I couldn't get to the remaining SVO edits tonight (it was a surprising amount of code to pick through considering the functionality) I'll finish and push them first thing tomorrow morning.
