### ISSUE TITLE
SVO text edit

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#95]
REf: https://github.com/drfwint/svo

On each of the decision pages, can you please add this text at the top of the page (under the title)

"Please make your allocation decision between yourself and the other person by moving the slider. You will be able to submit your decision after X second". 

I noticed that you cannot submit your decision instantly. You need to wait for sometime. Can you please incorporate that into the message above so that subjects would also know.

**Comment by mcdaij** [comment]
Note, this is not coded to a variable, it's hardcoded. This is because the amount of time before the next button is enabled is also hardcoded.

**Comment by billuraksoy** [comment]
Can you please explain a little bit more? How long do the subjects wait until they can proceed? Is it the same on all 15 decisions?

**Comment by mcdaij** [comment]
Yes, sorry, didn't see this. It is a constant set in a static JS file at 15 seconds.

**Comment by billuraksoy** [comment]
Can you please set it to 10 seconds instead and update the text accordingly. Thanks.

**Comment by mcdaij** [comment]
So I just double checked, that's hardcoded in the oTree source code. I'm not particularly familiar with that part of the JS structure (and it gets dynamically imported at run time so it's not just like a file I can change) so overriding it would probably take some time to get right.

**Comment by billuraksoy** [comment]
It is ok. dont worry about it. I make other changes to the instructions on earlier pages.
