### ISSUE TITLE
Subjects will not see the SVO results page. 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#96]
Please do not show the results page. However, I need all of these variables to be recorded (.e.g. svo_angle inequality_aversion_score alpha svo type )

**Comment by mcdaij** [comment]
So there's a bit of a problem here, SVO does not have any code to handle subjects dropping, or in fact, to handle that some subjects might have already dropped. I can add that (and I've been working under the assumption that you'd want me to) but it will take a bit more time, especially because of how tangled SVO is.

**Comment by billuraksoy** [comment]
We may need to chat about this. When is a good time for you? I am available today any other than 3-4

**Comment by mcdaij** [comment]
I was actually able to find a fix for this, so it shouldn't be a problem, I just have a little bit left to hook up and then all of the SVO will be done.

**Comment by billuraksoy** [comment]
ok great. Once you are done with the fixes, please describe here how this part of the code will handle dropouts.

**Comment by mcdaij** [comment]
So their setup isn't equipped to handle dropouts during their slider portion, and it would take significant retrofitting to do so, but I essentially just pushed in a constraint to the part where it calculates everyone's scores at the end, and told it that the only players it should be calculating for are the ones that didn't drop out (or had their partner drop out) in the first part.

**Comment by billuraksoy** [comment]
Is this a correct interpretation of what is going on:
all surviving subjects move to Part 2. They read the instructions, make 15 decisions. Once all decisions are made, they are grouped together to calculate the earnings. Next, they do the survey and see their earnings. 

Can you tell me more about when they are put in groups for Part 2 and exactly when the earnings are calculated for Part 2?

**Comment by mcdaij** [comment]
That is a correct interpretation as far as I can tell, although otree doesn't actually support *removing* people from anything, and they make the objects players will inhabit at the very start of the session so you can't actually remove them. Everyone's has a "player" object in every round of every app, even if their participant will never link with it. 

Given the parameters as they are they're not actually grouped in part 2 at all, their data is just taken from a master list (which my fix changed), compared, and sent back. The earnings are calculated once everyone (currently in the app) arrives at the end of the svo round 15, specifically on the wait page.

**Comment by billuraksoy** [comment]
Ok let me test it first and I may have more questions. Thank you. Can you please let me know when you are done with all issues?
