### ISSUE TITLE
survey

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#98]
Can you please add this question to the survey page?

#risks
    risk = models.IntegerField(
        label = 'Please answer the following question using a 1–10 scale, where 1 = completely unwilling and 10 = completely willing: Rate your willingness to take risks in general.',
        choices = [1,2,3,4,5,6,7,8,9,10],
        widget = widgets.RadioSelectHorizontal
        )

**Comment by billuraksoy** [comment]
Can you please move this risk question to the first survey page: mtpge/Survey
(sorry, I should have been clearer in the first place) 
This question can come after the ethnicity question.

**Comment by billuraksoy** [comment]
@mcdaij  Maybe you did not see this because I did not tag you in the comment? Can you please fix this?

**Comment by mcdaij** [comment]
Whoops, yeah, didn't see this sorry!
